### ISSUE TITLE
Timestamps in View Observations dialog are in UTC

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#100]
These are correctly stored on the server in UTC, and should be stored in the local data store in UTC as well.

They should be displayed in the dialog in local time not in UTC.

**Comment by dancunningham** [comment]
I believe https://github.com/projectbuendia/client/pull/95 fixes this?

**Comment by viniciusboson** [comment]
Yes, @dancunningham ... 
The timestamp is recorded as a long value and it is retrieved as UTC.
This #95 just changed the time formatter to display it in local time.

**Comment by llvasconcellos** [comment]
Fixed!
