### ISSUE TITLE
Test fields using profile `nutrition_chad4.csv` round all values to nearest integer

### ISSUE THREAD

**Issue by capnfabs** [projectbuendia/client#121]
Note: this isn't a problem that affects production, just the tests.

Currently, test fields are all truncated when they're displayed on the client. I entered the number "12.1" for a bunch of fields; here's the result:

![screenshot_2015-11-04-16-58-05](https://cloud.githubusercontent.com/assets/1336508/10933726/9af88792-8315-11e5-86f7-b7183e1fa9ab.png)

Note that:
- It's only for test fields - real fields work ok
- The values are stored with the decimal point on the server, it's just a formatting problem on the client side.

This causes 3/6 tests in PatientChartActivityTest to fail.

**Comment by llvasconcellos** [comment]
@dancunningham Might know how to fix this if I'm not mistaken.

**Comment by capnfabs** [comment]
I just added this profile to the profiles repo: https://github.com/projectbuendia/profiles/blob/master/integration-tests-en.csv

It has fixes for this issue. Note that I haven't reintegrated these changes into the profile that dev.projectbuendia.org is using.
