### ISSUE TITLE
Sync - unvoiding a voided observation isn't synced

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#143]
OK, here’s one thing that doesn’t work: unvoiding a voided observation (manually in OpenMRS web interface). It doesn’t appear back on the chart, even with a pull down refresh.

It’s an edge case so I’ll just raise it as an issue to fix later.

[yes, "synced" is now a verb instead of "synchronised"...]

**Comment by capnfabs** [comment]
This one isn't possible to fix under the current sync model. Here's why:
- Most records in OpenMRS store a record of when a record was edited, and by whom.
- For this reason, they've got `date_created`, `date_modified`, and `date_voided` database fields.
- Normally when you unvoid something, the `date_modified` field is set to the date the record was unvoided, and the `date_voided` field is cleared.
- Observations are special, however - they don't have `date_modified` field, and so when you unvoid one, the only thing that changes is the information about voiding.

Here's a dump of an observation, when voided, and then when unvoided.

``` diff
 {
     "obs_id": 200,
     "person_id": 1871,
     "concept_id": 999162169,
     "encounter_id": 45,
     "order_id": null,
     "obs_datetime": "2015-11-10 23:27:01",
     "location_id": 6,
     "obs_group_id": null,
     "accession_number": null,
     "value_group_id": null,
     "value_boolean": null,
     "value_coded": null,
     "value_coded_name_id": null,
     "value_drug": null,
     "value_datetime": null,
     "value_numeric": null,
     "value_modifier": null,
     "value_text": "Call family",
     "value_complex": null,
     "comments": null,
     "creator": 1,
     "date_created": "2015-11-10 23:27:47",
-    "voided": 1,
-    "voided_by": 349,
-    "date_voided": "2015-11-11 10:02:31",
-    "void_reason": "no longer reqd",
+    "voided": 0,
+    "voided_by": null,
+    "date_voided": null,
+    "void_reason": null,
     "uuid": "c668373f-b7d4-4ff1-8053-2395c9461a51",
     "previous_version": null
 }
```

Notice that the only thing that's different is those `voided` fields, there's no timestamp indicating when unvoided.

**Comment by capnfabs** [comment]
The biggest issue here is that our sync algorithm is not fully compatible with OpenMRS's data model, and there's nothing we can do about that without adjusting the sync algorithm. :(

As a workaround, I'd suggest doing what OpenMRS does for edits:
- voiding the old observation
- adding a new identical observation with the same data, referencing the old observation as a previous version.

It might be worth trying to upstream a change that addresses this problem in OpenMRS as well.

**Comment by capnfabs** [comment]
FYI, Pagination will fix this as a side-effect.
