### ISSUE TITLE
Sync - delay after completing form before results appear in chart

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#144]
I completed the Intensive Observations form and pressed Save.

It took 60s before the observations appeared in the chart.

This used to happen locally immediately; not needing to wait for a sync.

It should happen immediately so the nurse can verify that the observations have gone in correctly.

**Comment by capnfabs** [comment]
Good catch. The problem is that I changed the database schema to include Observation UUID and make it compulsory, but when we insert values locally to ensure immediate updates, we don't add a UUID.

The solution is to make the UUID field optional.

**Comment by capnfabs** [comment]
PR out: https://github.com/projectbuendia/client/pull/145
