### ISSUE TITLE
Allow form rotation to either Portrait orientation

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#173]
Chart is fixed to portrait and works either way up. (i.e. rotating by 180 degrees is allowed)

Form is fixed to portrait and only works one way up. (i.e. rotating by 180 degrees is allowed)

They should both allow rotating by 180 degrees (but not 90).

**Comment by capnfabs** [comment]
If someone wants to pick this up it's a one-line change in the AndroidManifest.xml for whichever AndroidManifest.xml the form activity is in.

**Comment by llvasconcellos** [comment]
I'm on it!
