### ISSUE TITLE
Sex not saved for new patients

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#175]
Testing on build 880.

When add a new patient with sex male or female, they appear without any sex.

**Comment by capnfabs** [comment]
The sex is being sent to the server correctly:

birthdate: "2013-07-08"
family_name: "Tt"
gender: "M"
given_name: "Ff"
id: "QQQ/123"

But isn't being stored correctly.

I suspect that this is related to when I renamed the "gender" field to "sex" in the protocol in accordance with a TODO.
