### ISSUE TITLE
Fix "Search by ID" to cope with ID prefixes

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#176]
It should match on just the ID (numerical) part

**Comment by capnfabs** [comment]
I suspect this will require server-side work in addition to client-side work.

**Comment by capnfabs** [comment]
Currently when you search by ID, the app also searches that ID against the server.

**Comment by dancunningham** [comment]
If this isn't an easy fix, we should just remove the "Search by ID" button as it doesn't work when patients have ID prefixes, as they are using in Bokoro.

**Comment by llvasconcellos** [comment]
The id and the prefix becomes the final id. Why not just to let the user enter alpha numeric chars in the search field?

**Comment by capnfabs** [comment]
I would suggest changing the SQL query powering this to

``` sql
WHERE id LIKE '{string}%' OR id LIKE '%/{string}%'
```

So that:
- if the user enters `123`, it matches `ABC/123` and `XYZ/123`
- if the user enters `ABC` it matches `ABC/123` and `ABC/456` and `ABCD/123`.

Thoughts?

**Comment by llvasconcellos** [comment]
@capnfabs Looks good.

**Comment by llvasconcellos** [comment]
I think it could be WHERE id LIKE '%/{string}%' directly.
On OpenMRS we need to set the values of the records:

patient.identifierPrefix = '%'
patient.identifierSuffix = '%'

from global_property table.

**Comment by llvasconcellos** [comment]
These would fix this problem:

https://github.com/projectbuendia/client/pull/243
https://github.com/projectbuendia/buendia/pull/71
https://github.com/projectbuendia/db-snapshot/pull/2

**Comment by capnfabs** [comment]
Great work Leonardo. I'm ok with these changes, but please note (everyone) that they'll require re-flashing the database.

**Comment by llvasconcellos** [comment]
@capnfabs Done!

**Comment by llvasconcellos** [comment]
The dev.projectbuendia.org mysql is also updated.

**Comment by dancunningham** [comment]
Actually the whole point of the Search by ID is for it to be a faster way to quickly get to an individual patient who you know the ID for. So part of the idea was that the numeric keyboard is faster to use.

The other thing it does is if it doesn't find the patient locally, it does the search on the server, so it can pull down a newly created patient. We thought it would be particularly useful in ATFC as patients are moving through the flow quickly after they are first created.

But we saw people were kind of confused about having two different patient search functions that are so similar.

I'll give this a test and see how it works!

**Comment by capnfabs** [comment]
Ok, so if we keep the numeric keyboard but use the other changes Leonardo has made, this should work great.
