### ISSUE TITLE
Capillary refill time showing up as {1,abbr}

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#203]
This is a select_one concept with two choices with very short labels that can serve as the long label and the abbreviated label.

When the label has a . e.g. "+. Mild (bilateral feet)", the text before the . is used as the abbreviated label, and the text after as the long label.

But when there is no dot, the whole text should be used for both. (or maybe the abbreviated one should be a truncation of the whole text).

**Comment by capnfabs** [comment]
I'm not sure that I understand the problem entirely - are you saying that:
- It's possible to define choices for a `select_one` with `[short].[longgggggggggggggggg]`
- If you define a `select_one` with just `[short]`, for long fields you see the string `"{1,abbr}"`?

**Comment by llvasconcellos** [comment]
@dancunningham Can you give us a profile example?

**Comment by llvasconcellos** [comment]
OK. I see the problem using nutrition-itfc-104.csv.

**Comment by llvasconcellos** [comment]
The problem is that Capillary refill answer has less than 3 chars (MAX_ABBR_CHARS).

**Comment by llvasconcellos** [comment]
{1,abbr} is the default format for all observations?
