### ISSUE TITLE
"Failed to fetch form from server"

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#204]
I'm getting this periodically, as well as when I try to load up any of the following forms from profile "nutrition-itfc-102-v8.csv":
- Anthropometrics
- Diagnosis & Plan (long)
- Diagnosis & Plan (short)
- Immunisations History

Other forms do work.

App build 904 connected to dev.

**Comment by dancunningham** [comment]
I notice that on the forms in question, the first field appears incorrectly before the “Encounter” group...

Anthropometrics - http://dev.projectbuendia.org:9000/openmrs/admin/forms/formEdit.form?formId=94

Diagnosis & Plan (text) - http://dev.projectbuendia.org:9000/openmrs/admin/forms/formEdit.form?formId=103

Immunisations History - http://dev.projectbuendia.org:9000/openmrs/admin/forms/formEdit.form?formId=93

**Comment by dancunningham** [comment]
One key difference seems to be that they don’t start with a section or select_multiple field (which creates a section)

**Comment by llvasconcellos** [comment]
The problem I found was that _sections_ are mandatory. At least each form has to have one section.
You can call the section **[invisible]** to avoid it's header to be displayed.

**Comment by llvasconcellos** [comment]
So, to avoid future problems I'm making sections not mandatory in the CSV profile so the profile_apply script will detect if you have declared a section and if not it will create a section called **[invisible]** automatically.

**Comment by dancunningham** [comment]
Fixed by 0e45cf
