### ISSUE TITLE
Wrong time displayed in pop-up dialog when 2nd note added later in the day

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#205]
Patient ABC/246. Albert Bisset on dev.projectbuendia.org

I filled in the Admissions form at 1:01am, including a note.

I filled in the Record Immunisations form at 1:47am, including a note.

They both show up with the time 1:01am.

**Comment by dancunningham** [comment]
Just added another with time 1:50am, making sure that was the time set in the form, and it's also showing up as 1:01am.

**Comment by dancunningham** [comment]
This is P1 because we would really like to use the Notes pop ups in addition to the Notes panel in the pilot, but if it isn't fixed, we can just use the Notes panel.

**Comment by llvasconcellos** [comment]
This might be the same problem of the wrong time in orders.

**Comment by capnfabs** [comment]
Yeah I reckon it's the same problem. Especially if it shows up ok in the notes panel.

**Comment by llvasconcellos** [comment]
This is a duplicated issue and was solved along side with this:
https://github.com/projectbuendia/client/issues/224
