### ISSUE TITLE
FakeSyncManager.java won't build.

### ISSUE THREAD

**Issue by llvasconcellos** [projectbuendia/client#207]
/home/leonardo/Projects/Buendia/direct/client/app/src/androidTest/java/org/projectbuendia/client/FakeSyncManager.java:41: error: startFullSync() in FakeSyncManager cannot override startFullSync() in SyncManager
    @Override public void startFullSync() {
                          ^
  overridden method is static
/home/leonardo/Projects/Buendia/direct/client/app/src/androidTest/java/org/projectbuendia/client/FakeSyncManager.java:41: error: method does not override or implement a method from a supertype
    @Override public void startFullSync() {
    ^

**Comment by capnfabs** [comment]
Actually, a few of the tests are broken. Investigating now.
