### ISSUE TITLE
Error message when saving Admission form

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#218]
When I try to save a fully completed admission form I am getting this error message:

"Sorry, form save failed!: Index 0 requested, with a size of 0"

This is with profile nutrition-itfc-104.csv on dev.projectbuendia.org with app build 905.

**Comment by dancunningham** [comment]
Cleared data and upgraded to build 908 and it works, closing for now.

**Comment by dancunningham** [comment]
OK, when I fill in the whole form this is still happening. Re-opening!

**Comment by dancunningham** [comment]
This is really weird.

When I fill in each of the fields one at a time (each in its own submission), it works.

When I fill in all of them in one form submission, the error occurs. So it's some combination of them that seems to be causing the problem.

**Comment by dancunningham** [comment]
Now getting this on Edison for the Anthropometrics form too.

**Comment by llvasconcellos** [comment]
Could not reproduce it with the latest client / server builds and with the specified profile.
Feel free to open again if the problem occurs.
