### ISSUE TITLE
Properly attribute orders to user who created/edited/recorded them

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#222]
We've got a special OpenMRS user with ID #349 with the username "buendia". All API calls are done impersonating that user because we never implemented proper authentication for users of the Buendia tablet app. This means all order management is recorded against user #349 - "buendia", not the user of the Buendia tablet app.

It should be recorded against the provider corresponding to the user logged in to the Buendia tablet app.

**Comment by capnfabs** [comment]
We properly attribute orders as of https://github.com/projectbuendia/buendia/pull/58.

Note that this isn't done using auth, though, but using a mechanism similar to what observations use - just an additional json field that has the user's UUID.
