### ISSUE TITLE
Treatment frequency no longer appearing

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#225]
In the chart view it is meant to show both the Dosage and the Frequency on the second row in the chart.

This used to be working.

**Comment by llvasconcellos** [comment]
@dancunningham: I tracked down the changes and noticed that before we had the {{order.instructions}} displayed in the chart, now we have {{order.medication}} on top of {order.dosage}}.
This change was added in feature/ping-text-styles branch.
https://github.com/projectbuendia/client/blob/feature/ping-text-styles/app/src/main/assets/chart.html
I changed order.dosage to order.instructions and it looked like this:
![device-2016-01-19-193315](https://cloud.githubusercontent.com/assets/1710823/12432642/88525e88-bee3-11e5-922c-3224d3afadf2.png)

**Comment by capnfabs** [comment]
This could have been as a result of the Edit Orders changes.

**Comment by llvasconcellos** [comment]
@capnfabs It seems a lot earlier.
