### ISSUE TITLE
Chart not updated after entering data twice in quite quick succession

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#251]
I filled in the Surveillance form with resp rate, heart rate, AVPU and temp.

It showed OK on the chart.

Then I filled it in again, with different values for those concepts (all except AVPU).

The chart flashed, looking like it had updated, but the new values were not there.

When I left the patient view and went back in, they do appear.

Client build 932 connected to dev.projectbuendia.org

**Comment by llvasconcellos** [comment]
Probably related to @capnfabs recent changes on chart reloading.

**Comment by capnfabs** [comment]
I think this is #125.
