### ISSUE TITLE
Observation dialog - title set to "The page at 'file://' says:

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#27]
Title should be the name of the concept and the date.
e.g.
Oedema - 5 Sep

**Comment by llvasconcellos** [comment]
This is the way chrome works when using alert() function. It's a security measure. The only way to avoid this is to create our own alert dialog.

**Comment by capnfabs** [comment]
It's not too hard to fix though: http://stackoverflow.com/questions/10635563/modify-alert-title-javascript-in-android-webview

**Comment by zestyping** [comment]
Wow, that's cool!  Maybe we could use that technique together with
Html.fromHtml to do the details popup in HTML as well, which would offer
lots more formatting flexibility.

**Comment by capnfabs** [comment]
:+1:

**Comment by G1DR4** [comment]
fixed, thx fabian.
