### ISSUE TITLE
Observation dialog - rounding

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#28]
It's rounding values; it shouldn't. It should show the full value for floats.

e.g. Temperature - 37.5 is being rounded to 38.

**Comment by zestyping** [comment]
Ah yes.  The default cell-details-dialog format (i.e. captionFormat) for numbers is "0" in ui.chart.Row.DEFAULTS, and "0" causes the number to be rounded with no decimal places.

https://github.com/projectbuendia/client/blob/0938b8128367cf06710ac031d56697a586db7cad/app/src/main/java/org/projectbuendia/client/ui/chart/Row.java

**Comment by llvasconcellos** [comment]
It's fixed for temperature. If it happens for other observations please reopen.
