### ISSUE TITLE
Log Screen -> Add New User -> Very Long Name gives "Unknown Error"

### ISSUE THREAD

**Issue by saratheneale** [projectbuendia/client#291]
1. Open App with Log on options
2. Click New User
3. In both fields put a very long string. 
Ex: "AVeryLongLongLongLongSooooooLongNameItIsSoLong" / "StillALongNameAVeryLongLongLongLongSooooooLongNameItIsSoLong"
4. Submit

**Result**: Android Toast Text - "Unknown Error" and the user is not created
**Expected**: Either a char limit or the user to be created. 

Possibly related: https://github.com/projectbuendia/client/issues/198

**Comment by zestyping** [comment]
Just took a quick look at this in the debugger.  The server is indeed rejecting the name due to its length:

> com.android.volley.VolleyError: ServerError : 500 'Person(personId=null)' failed to validate with reason: names[0].familyName: The {0} value is too long.  The maximum length is {1}.

...but the app is not showing this explanation to the user.

**Comment by zestyping** [comment]
The server-side limit is 50 characters.  The simplest fix would be to enforce a 50-character limit in the UI.

**Comment by zestyping** [comment]
This was closed by #349.

@mjanes To make the PR automatically close the issue, you have to put "Closes #291" in the PR description (not just "#291").
