### ISSUE TITLE
Enhancement: Treatments design with adaptive individual columns

### ISSUE THREAD

**Issue by ivangayton** [projectbuendia/client#297]
Here's the idea of the treatments section of the chart.

The principle is:

- Day columns always align with the days in the chart
- Within a day, each row in Treatments has its own individual number of columns, and therefore width of subdivided columns. 

![Treatments Design](https://user-images.githubusercontent.com/5991943/59711808-a9cc5600-91c0-11e9-9848-2769056c8ad1.png)

And the proposed entry form for treatments:
![Treatments entry form](https://user-images.githubusercontent.com/5991943/59711816-af29a080-91c0-11e9-8218-b4b6fddbebe3.png)

**Comment by zestyping** [comment]
The main work of the chart display is now done (at least to a prototype level) in #372.  Closing this and opening new issues #375 and #376 for the remaining smaller changes to the treatment order dialog.
