### ISSUE TITLE
Search -> Should searching middle of name work?

### ISSUE THREAD

**Issue by saratheneale** [projectbuendia/client#309]
1. Have `Darth Vader` in Patient List
2. Search `ader`
Result: No patients
Expected: `Darth Vader`

**Comment by zestyping** [comment]
The search query is matched against the beginning of any word in the name.  See [NameFilter.java](https://github.com/projectbuendia/client/blob/master/app/src/main/java/org/projectbuendia/client/filter/matchers/patient/NameFilter.java).  (If we want to change this behaviour, this would be the place to make the change.)

**Comment by mjanes** [comment]
@saratheneale tells me that this is still a nice to have, and is easy.

**Comment by zestyping** [comment]
Please don't re-open issues that are closed, without discussion.  This was a deliberate design choice.  Indeed, we might revisit it, but not this way.
