### ISSUE TITLE
Updating data in the same minute does not display most recent first

### ISSUE THREAD

**Issue by saratheneale** [projectbuendia/client#314]
In the patient record, I made a new round and immediately update the Respiratory rate only. (Within the same minute). This was only tested when manually backdating the device time.

1. Manually set date to the past.
2. Open app and patient and add a new round. 
3. Save the data. 
4. Pretend you made a mistake and need to correct the respiratory rate! 
5. Make a new round and update the Respiratory rate to a new value
6. Save the data.
Result: The old resp rate is displayed. 
**Expected**: The new one should be displayed. 

7. Click the respiratory rate square. 
8. Observe Both values are there with the same hour:minute timestamp.

**Comment by saratheneale** [comment]
I confirmed that this also happens if you submit two Ebola Test Results in the same minute.

**Comment by zestyping** [comment]
If anyone wants to look into this, any investigation would be helpful.  Note what you find in comments on this issue.  Thanks!

**Comment by zestyping** [comment]
@mjanes If you have time after the other issue, it would be great to learn more about why this is happening.  Let me know what you find.

**Comment by mjanes** [comment]
If the most recent observation points occur within the same minute (ie 17:38), it is not displaying the most recent.

Uncertain what the cause of. Looking at ObsPoint.compareTo(), it is using Instant.compareTo() which goes by millisecond. Searching for any comparison using minute.

Or perhaps somewhere in the conversion of ReadableInstant to Instant, or the creation of ReadableInstant, some precision is being lost.

**Comment by mjanes** [comment]
Would also note that this does not happen every time. You can take make an initial observation for a row, and then make another observation within less than a minute, and *sometimes* will display the the most recent.

**Comment by mjanes** [comment]
If the ChartRenderer is not showing the most recently taken value, the ViewObservationsDialogFragment is also not ordering the ObsRows as expected. Looking in ChartDataHelper.getPatientObservationsByConceptMillis, which feeds the ViewObservationsDialogFragment, the query does order by ENCOUNTER_MILLIS.

The ENCOUNTER_MILLIS of the individual ObsRows returned are ordered properly.

Which I believe means that either when creating an observation, sending it to the server, or getting back from the server (?), the millisecond time of observation creation is not being recorded properly.

**Comment by mjanes** [comment]
Realizing that the time of observation can be specified in the "Clinical Observation" page (Patient Chart Activity/Controller?). Believe through an instance of DateTimeWidget. With that, uncertain how observations should be ordered, if both are specified to have occurred at the same time.

As of yet, I do not know why two observations specified to have occurred in the same minute can end up stored in the db with different ENCOUNTER_MILLIS values.

**Comment by mjanes** [comment]
@saratheneale If two observations are specified to have occurred on the same minute, what is the spec for how they should be ordered?

**Comment by mjanes** [comment]
Summarizing observations:

Order of observations displayed is consistent between the ChartRenderer grid and the observation dialog. The observation value displayed in the grid, matches the first/top observation displayed in the observation dialog.

Looking at ChartDataHelper.obsrowFromCursor(), multiple observations taken in the same minute, have the same `millis` value.

I assume that on creating a new observation, converts the "date and time of encounter" to millisecond by the minute picked on that date spinner. Everything will be rounded to minute, though it's being stored as millisecond.

I am uncertain how the FormEntryActivity gets the time of the encounter from that calendar + time spinner. The clinical observation form looks to be created dynamically.

**Comment by zestyping** [comment]
Yeah, the problem is that the encounter form initializes the datetime to the current time, but the datetime widget only shows minutes and the form only records the time rounded to the minute.
