### ISSUE TITLE
css_class not being applied for select_one with abbr

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#32]
For this row in my profile spreadsheet, within tiles (and similarly within grid):

```
type        select_one
required
concept     460
label       Oedema
format      {1,abbr}
css_class   {1,select,777000104:abnormal;777000105:abnormal;777000106:critical}
```

The CSS class does not look like it is being applied to the abbreviation or the second line in the tile, or to the abbreviation in the grid.

A similar grid row does seem to be getting the CSS class applied:

```
type        select_one
required    yes
concept     1643
label       Paracheck
format      {1,select,703:+ve;664:-ve;1138:?;}
css_class   {1,select,703:critical;664:good;1138:borderline}
```

There are some differences:
- it is a required row
- it has a more customised format
- it is only in the grid, not in the tiles

**Comment by G1DR4** [comment]
checking

**Comment by llvasconcellos** [comment]
This is working now.
