### ISSUE TITLE
Add up/down buttons to chart view to scroll without swiping

### ISSUE THREAD

**Issue by daisuke-plangrid** [projectbuendia/client#338]

**Comment by saratheneale** [comment]
Please consider these views too for scroll buttons: 

- Right / Left for Patient Record with lots of rounds per day and lots of days
- up / down for Patients List
- up / down for Locations screen depending on how many Beds you have

**Comment by krtonga** [comment]
Notes from discussion with Ping: 
- How much to scroll? On up/down probably the last visible row should jump to the top. Don't hardcode anything - use the boundaries of the columns to determine how far.
- Animation? Not on version 1. 
- How to? This will be in javascript in `chart.html`.

**Comment by zestyping** [comment]
Hi @krtonga, I jumped in on this one because we decided it was urgent for Thursday.  Sorry to steal it away from you!
