### ISSUE TITLE
Notes dialog pops up twice

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#34]
When you tap on the Note icon in the grid, it first comes up as it should, then when you press OK another dialog comes up immediately after which is kind of empty just with a timestamp:

![notes dialog](https://cloud.githubusercontent.com/assets/961528/10089829/2d161862-6320-11e5-9b31-0050e3ef41e1.png)

**Comment by zestyping** [comment]
This was fixed as part of pull request #35 with a call to event.stopPropagation().
