### ISSUE TITLE
UI -> Better Wrapping for Essential Status Text 

### ISSUE THREAD

**Issue by saratheneale** [projectbuendia/client#363]
App version: (the number after "Buendia" on the starting screen)
Screen or dialog:

#### Use case or problem addressed by this proposal
Better Mobile Responsiveness. Better experience on smaller devices. 
#### Proposed feature or improvement

Small UI suggestion of making the essential statuses more responsive on mobile. On Android phone, it looks like "Preg / nant / IV / fitted / Oxy / gen / Can- / not / eat" on ~8 lines

**Comment by saratheneale** [comment]
Pixel 2

![Screenshot_20190628-120552](https://user-images.githubusercontent.com/3619338/60365373-64b4da80-999d-11e9-9912-9ebb20cd8558.png)

**Comment by zestyping** [comment]
This will probably be addressed when we replace the Android-coded first row of elements with HTML tiles.

**Comment by zestyping** [comment]
The tiles have been reworked completely and this text is no longer present.  The tiles are now configured in the profile..
