### ISSUE TITLE
Adding a treatment with 958 days causes patient chart to crash

### ISSUE THREAD

**Issue by saratheneale** [projectbuendia/client#366]
Adding a Treatment crashed the app. Log attached. 

[addtreatment.txt](https://github.com/projectbuendia/client/files/3340530/addtreatment.txt)

**Comment by zestyping** [comment]
This is an OutOfMemory error trying to render the chart.  Any further attempt to load this patient (ID 1234) now reliably causes this crash.

**Comment by zestyping** [comment]
Oh, I see why.  The newly added treatment order is for 958 days, and the tablet doesn't have enough memory to make a table 958 days wide with >40,000 cells in it.
