### ISSUE TITLE
Observation -> Can't null out or false symptoms

### ISSUE THREAD

**Issue by saratheneale** [projectbuendia/client#367]
App version: (the number after "Buendia" on the starting screen)
Screen or dialog:

#### Steps to replicate the problem

1. Go to Patient Observation. Click New Observation
2. Click Nosebleed.
3. Save
- [ ] Confirm Nosebleed is in observation chart. 
4. Click New Observation
5. Try to remove the nosebleed observation. It's not obvious
6. Click another symptom
7. Save. 

#### Actual behaviour
You can't remove the nosebleed

#### Expected behaviour
There should be a way to remove the nosebleed symptom in the round.

**Comment by zestyping** [comment]
This comes down to conflation as to the meaning of "didn't tap the symptom" — does it mean "I checked and the patient does not have the symptom" or "I did not check and don't know whether the patient has the symptom"?

This is arguably a design bug, but it was a deliberate choice in 2014.  One option for solving this is to provide specific "Yes", "No", "Unknown" states for each symptom, but we're not certain it would work best for medics.
