### ISSUE TITLE
Patient List -> New Patient doesn't show up.

### ISSUE THREAD

**Issue by saratheneale** [projectbuendia/client#369]
App version: (the number after "Buendia" on the starting screen)
Screen or dialog:

#### Steps to replicate the problem

1. Made a new patient - 10102
2. clicked on Triage in Locations to see if they were there.

**Result**: Did not see patient in Triage List after adding. 

**Expected** to see patient list there.

**Comment by zestyping** [comment]
Just tried adding patient 753, Steven Universe, and the new patient appears for me in Triage.  Might need more specific conditions to replicate this?
