### ISSUE TITLE
Sync Issues

### ISSUE THREAD

**Issue by saratheneale** [projectbuendia/client#377]
App version: (the number after "Buendia" on the starting screen)
Screen or dialog: Patient Chart

#### Steps to replicate the problem
User two devices. 
1 device is the "viewer"
1 device is the "editor"

1. Each of you bring a Patient Chart up 
2. Tester Edit: Add a new round (clinical observation) with a variety of data. 
3. Tester Edit: Save the patient

#### Actual behaviour
Tester View: Patient has stale data. 

#### Expected behaviour
Expected: Tester View: The patient updates with the new Round.

**Comment by saratheneale** [comment]
Note: I haven't replicated this yet.

**Comment by zestyping** [comment]
Okay.  Please apply the "needs replication" label to bugs that need replication, thanks!

For this issue, when trying to replicate, it's important to measure how much time has passed.  The patient should update on the second tablet after one minute.

**Comment by saratheneale** [comment]
Closing this issue in favor of more specific sync issues and test cases.
