### ISSUE TITLE
Syncing while 2 devices update a patient chart 

### ISSUE THREAD

**Issue by saratheneale** [projectbuendia/client#378]
Screen or dialog: Ebola Test
Tested with PID: 33332222

From testing party notes: 

1. Get two people to update an ebola test at the same time.
2. Person A will udpate first with 5/10. 
3. Person B will update next with 20/20.
**Result**: 
After the first update of 5/10 the **actual** result was -/10 displayed, **Expected** 5/10
After the second update of 20/20 the **actual** result was 5/20, **Expected** 20/20
After some time they both updated to 20/20

**Comment by zestyping** [comment]
This is due to displaying the wrong fields for the Ebola Test; this is corrected in newer profiles.
