### ISSUE TITLE
Treatments -> 3 days does not give full dose

### ISSUE THREAD

**Issue by saratheneale** [projectbuendia/client#384]
App version: (the number after "Buendia" on the starting screen)
Screen or dialog: `1d2acbb` release tagged under 0.13.1

#### Steps to replicate the problem

1. Add a Treatment to a Patient. Asprin 400 mg, frequency 2, give for 3 days. 

#### Actual behaviour
On the Patient Grid, I see 4 doses given over 3 days. 

#### Expected behaviour
I expected to see  5 doses given over 3 days. I expected the day 3 have 2 doses

#### Screenshots 
Here's what it looks like in the rounds: 
![Screenshot_20190703-165513_Buendia](https://user-images.githubusercontent.com/3619338/60631323-cfa64d00-9db3-11e9-91e2-aa38ffa620de.jpg)

Here's what the Aspirin Treatment looks like: 
![Screenshot_20190703-165523_Buendia](https://user-images.githubusercontent.com/3619338/60631341-e6e53a80-9db3-11e9-901d-a68dee5c31d4.jpg)

**Comment by zestyping** [comment]
I'm trying to replicate this bug and haven't been able to.  When I order 2 doses per day for 3 days, I get the expected six doses.  I tried placing this order both during the first half of the day and the second half of the day, and got the expected results in both cases:

![aspiron-6doses](https://user-images.githubusercontent.com/236086/60797509-3ca74300-a124-11e9-8ad4-a2b0208cf031.png)

The screenshot example in the main issue report above looks like what you should get if you order Aspirin for 2 days at 2 doses per day, and Zyrtec for 3 days at 2 doses per day.  Is it possible that this is what was actually ordered in the example?

**Comment by zestyping** [comment]
The treatment order dialog (especially the logic for the duration and frequency of a repeated treatment) has been substantially reworked since this issue was reported, and the problem doesn't seem to occur any more.
