### ISSUE TITLE
Server Error on Dual Initial Sync

### ISSUE THREAD

**Issue by saratheneale** [projectbuendia/client#398]
App version: Buendia 0.14
Screen or dialog: Sync Observations

#### Steps to replicate the problem
Cannot replicate. 
1. Have 2 devices with fresh Buendia installs. Be on the users screen before the initial Sync
2. On the Users Screen, Click Guest User on both at the same time. (or one after the other).

n/a. Tried uninstalling and reinstalling and couldn't do it. 

#### Actual behaviour
On my phone, I got a server error. See screenshot below. I also saw a Red Toast message that said "Null Response."

#### Expected behaviour
Expected server to return data and sync without error. 

### Bug Report
Looks like its just wifi info. 
[initialSyncNotes.txt](https://github.com/projectbuendia/client/files/3379001/initialSyncNotes.txt)

#### Screenshots 
![Screenshot_20190710-113220](https://user-images.githubusercontent.com/3619338/60996010-a3855180-a308-11e9-94e0-c592e615275b.png)

**Comment by zestyping** [comment]
Sync has been reworked and improved quite a bit since this issue was reported, and we don't see errors like this any more.
