### ISSUE TITLE
Bug with #35: UUIDs showing up instead of names

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#46]
This relates to pull request #35, when I installed from the ~client-wip build (which I'd merged that pull request into) and applied the profile "nutrition-dan14-with-graph.csv".

This might actually be a couple of separate bugs.

There’s something weird going on with some of the concepts on dev.projectbuendia.org. I’m seeing UUIDs showing up instead of names for some concepts.

This relates first to Oedema - http://dev.projectbuendia.org:9000/openmrs/dictionary/concept.htm?conceptId=460

777000103 "-. None" has been replaced with 777000103 with English name “Order executed” and English (UK) name “-. None”. The UUID is now "buendia-concept-order_executed”. In the patient chart grid rows, it is the UUID that shows up instead of the name or abbreviated form.
http://dev.projectbuendia.org:9000/openmrs/dictionary/concept.htm?conceptId=777000103

777000104 has similarly become merged with "Order described in free text instructions”

777000105 "++. Moderate (Feet and legs)” and 777000106 "+++. Severe (Face, feet and legs)” seem to be fine, though in the grid and tiles, the UUID is shown instead of the name.

Also, the Consciousness (AVPU) answer “A. Alert” is showing up as its UUID instead of name “160282AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA”
http://dev.projectbuendia.org:9000/openmrs/dictionary/concept.htm?conceptId=160282

Several weird things to investigate and fix:
1. Why have these concepts been merged with “Order executed” concepts?
2. Why does that concept have the UUID "buendia-concept-order_executed” instead of a hexadecimal UUID - is that OK?
3. Why are the UUIDs showing up instead of the names?

**Comment by dancunningham** [comment]
![image](https://cloud.githubusercontent.com/assets/961528/10269811/bf678592-6ad8-11e5-811b-b2fb4cbc11a2.png)

**Comment by zestyping** [comment]
Oops!  I did see these label rendering problems as well when I was developing this, and fixed them in my last commit to this branch.  But I neglected to push the fix — the Github repo has been 1 commit behind my local branch all this time.  I've pushed to origin, which should address this.

In addition, yes, it is odd that the UUIDs for Oedema severities have collided with the UUIDs for order execution.  I believe this is a result of uploading and applying a lot of profiles — we may have inadvertently specified conflicting IDs, or previously fixed bugs in buendia-profile-apply may have left behind messy data in the database.  But when the new profile is applied properly, it causes the right things to appear even if they have weird IDs in the database.  So, I think that messiness is not related to this PR — it was there in the database, and I'm pretty sure it would all be cleaned up if we wiped all our custom concepts (i.e. all concepts with IDs >777000000) from the database and applied the profile fresh.

In any case we don't have to do the database fix for this to work just fine for the field test.  This should be usable in its current state now.

**Comment by zestyping** [comment]
Note it would be nice to clean up the database before we announce a public release (as we don't want all these messy experimental concepts in every future deployment).  As I think it's a low priority before the trip, the easiest course is to do a server release without making any big announcements, and then we can do a cleaner release later.

**Comment by llvasconcellos** [comment]
I've tested and it seems fixed.
