### ISSUE TITLE
Bug with #35: All notes showing up as null

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#47]
This relates to pull request #35, when I installed from the ~client-wip build (which I'd merged that pull request into) and applied the profile "nutrition-dan14-with-graph.csv".

With this set up, the notes icon correctly appears whenever notes have been recorded.

When you tap on it, the dialog just displays a blank space where the note should be:

![image](https://cloud.githubusercontent.com/assets/961528/10269795/8449436a-6ad8-11e5-9130-c376d9319184.png)

**Comment by zestyping** [comment]
Ah, turns out this is very easy to fix!  On line 81 of chart.html, the line

```
                          + {{point.value | js}}
```

should be changed to

```
                          + {{point.value.text | js}}
```

because the text of the note is now stored in the `text` member of the ObsValue object.

**Comment by llvasconcellos** [comment]
I tested it and it's working, although the [test] notes behave differently.
![test-notes](https://cloud.githubusercontent.com/assets/1710823/10300906/1d4de96c-6bd3-11e5-9130-9d4e782149b5.png)

![image](https://cloud.githubusercontent.com/assets/1710823/10300930/6379a05c-6bd3-11e5-9f9d-f7f5972d113d.png)

![image](https://cloud.githubusercontent.com/assets/1710823/10300920/4751730a-6bd3-11e5-9a95-4c8091c4320e.png)
