### ISSUE TITLE
Blank form appearing at top of menu

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#53]
This is with nutrition-chad4.csv loaded.

Client version 809. Server version 0.5

![screenshot_2015-10-06-15-30-53](https://cloud.githubusercontent.com/assets/961528/10311611/6148ec86-6c3f-11e5-952b-10a6820cdc63.png)

**Comment by llvasconcellos** [comment]
@dancunningham can you attach nutrition-chad4.csv here?

**Comment by dancunningham** [comment]
Not seeing this any more with latest profile, though would be interesting to know what caused it so we can avoid it in the future.

Here's nutrition-chad4.csv:
https://www.dropbox.com/s/1s1tzt1bvbu1wd5/nutrition-chad4.csv?dl=0

**Comment by dancunningham** [comment]
By the way you can download profiles from: http://dev.projectbuendia.org:9000/openmrs/module/projectbuendia/openmrs/profiles.form

**Comment by llvasconcellos** [comment]
@dancunningham I can't apply nutrition-chad4.csv

![image](https://cloud.githubusercontent.com/assets/1710823/10807428/c4550db2-7dc6-11e5-93ca-65eb6e0884b2.png)

**Comment by llvasconcellos** [comment]
Python Trace:
Error applying profile: nutrition-chad4.csv

``` python
Traceback (most recent call last):
  File "/usr/bin/buendia-profile-apply", line 501, in <module>
    apply(read_csv(sys.argv[1]))
  File "/usr/bin/buendia-profile-apply", line 497, in apply
    main()
  File "/usr/bin/buendia-profile-apply", line 147, in main
    apply_forms(tabs['form'])
  File "/usr/bin/buendia-profile-apply", line 337, in apply_forms
    put_form(form_rows)
  File "/usr/bin/buendia-profile-apply", line 353, in put_form
    apply_form(rows, form_id)
  File "/usr/bin/buendia-profile-apply", line 451, in apply_form
    put_coded_concept(option_concept_id, option_label, LOCALE)
  File "/usr/bin/buendia-profile-apply", line 218, in put_coded_concept
    put_concept(concept_id, name, locale, coded_datatype, obs_class)
  File "/usr/bin/buendia-profile-apply", line 241, in put_concept
    get_datatype_name(new_datatype_id)))
ValueError: Concept 138868: cannot change type from N/A to Coded
```

**Comment by llvasconcellos** [comment]
That error was on my local server. On dev.projectbuendia.org works fine.

**Comment by viniciusboson** [comment]
Here a handy provisory script to handle this ..

```
select concept.concept_id, concept.uuid, datatype.concept_datatype_id, datatype.name, name.name
from concept concept 
join concept_name name on concept.concept_id = name.concept_id
join concept_datatype datatype on concept.datatype_id = datatype.concept_datatype_id
where concept.concept_id in (XXX);

update concept set datatype_id = YYY where concept_id = XXX;
```

The 'N/A' id is 4 and 'Coded' id is 2. You can manually update those concepts to apply for this specific profile.

**Comment by zestyping** [comment]
You can also turn off the type check in profile_apply if you want.  But the
type check is there for a reason — OpenMRS is unhappy if you change the
type of a concept while it is running.  It will return the wrong type.  You
can shut down the server, change the concept type, and restart the server.
profile_apply doesn't do this automatically because it takes 5 minutes of
downtime.

**Comment by dancunningham** [comment]
Doesn't seem to be an issue any more
