### ISSUE TITLE
P0 - Application is not allowing to record treatment given the day after it was prescribed

### ISSUE THREAD

**Issue by viniciusboson** [projectbuendia/client#62]
Steps to reproduce this bug:
. Go to Patient chart (Select a user, then a location and then a patient)
. Add a new treatment not entering any duration  (i.e. continue indefinitely).
. Add any observation (to not collapse the empty  'today column')
. Change the system date, adding one day from today. 
. Reload the patient chart and try to tap in the treatment cell. No dialog comes up.
. This is client 822.

![screenshot_2015-10-11-10-41-36](https://cloud.githubusercontent.com/assets/665045/10395374/9fa09e16-6e6a-11e5-9fd1-142fb6d529ff.png)

**Comment by G1DR4** [comment]
http://dev.projectbuendia.org:9000/openmrs/ws/rest/v1/projectbuendia/xforms/buendia-form-add_test_results?v=full returns no errors.

**Comment by zestyping** [comment]
Figured this out.  See https://github.com/projectbuendia/client/pull/67

**Comment by zestyping** [comment]
See also https://github.com/projectbuendia/client/pull/66 (not the same bug, but also affecting order execution counts)

**Comment by G1DR4** [comment]
checking if fixed.

**Comment by viniciusboson** [comment]
i've just tested it again locally and now it's working.
Two week ago, when i tested it, sometimes it was working and other times doesn't.
The error was probably some latency issue.

**Comment by llvasconcellos** [comment]
It's working.
