### ISSUE TITLE
Temperature is not being updated on patient chart.

### ISSUE THREAD

**Issue by llvasconcellos** [projectbuendia/client#85]
This was caught by PatientChartActivityTest -> testEncounter_latestEncounterIsAlwaysShown().

When you record a temperature more two or more times in a row some of it's values goes missing.

**Comment by dancunningham** [comment]
Tested with 3 updates to temperature within a minute and it seems to work fine, even after doing a pull down refresh from patient list. Closing this!

**Comment by capnfabs** [comment]
@dancunningham I reckon you're still observing the same problem in @viniciusboson's PR #172. But we're also tracking this in #125 so let's keep tracking it there.
