### ISSUE TITLE
Translations appear to be inconsistent.

### ISSUE THREAD

**Issue by capnfabs** [projectbuendia/client#98]
For System locales set to: en_UK, en_AU

The patient chart appears to be in a combination of French and English.

![screenshot_2015-10-27-12-17-30](https://cloud.githubusercontent.com/assets/1336508/10749623/800f2266-7ca7-11e5-8045-3ed5b8717ce3.png)

Note that the WebView and the Menu are in French, but the rest of the UI is in English.

**Comment by capnfabs** [comment]
Digging into the code, those menu items are generated from form names.

**Comment by dancunningham** [comment]
At the moment the chart and form labels are determined by the loaded profile, independently from the UI which is determined by the system language.

It would be useful to have multilingual profiles such that changing the system language also changes which labels are loaded from the profile. This is more of a feature request than a bug.

**Comment by G1DR4** [comment]
:+1:
